services:
  frontend:
    image: frontend-image
    ports:
      - "80:80"
    volumes:
      - product-images:/usr/share/nginx/html/uploads
  backend:
    image: backend-image
    ports:
      - "8080:8080"
      - "5005:5005"
  environment:
    SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/shoppingweb
    SPRING_DATASOURCE_USERNAME: root
    SPRING_DATASOURCE_PASSWORD: Alan0818
    JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
  volumes:
    - product-images:/app/uploads
  db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: shoppingweb        # 資料庫名稱
      MYSQL_USER: root                   # 使用者名稱
      MYSQL_PASSWORD: Alan0818              # 使用者密碼
      MYSQL_ROOT_PASSWORD: Alan0818           # root 密碼
    ports:
      - "3306:3305"                      # MySQL 預設埠
    volumes:
      - db_data:/var/lib/mysql           # 資料庫資料持久化


